sudo: false

language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs --prefer-source
  - composer info -i

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit
