sudo: false

language: php

php:
  - 7.0
  - 7.1
  - 7.2

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs --prefer-source
  - composer info -i

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit
