name: "Continuous Integration"
on:
    pull_request:
    push:
        branches:
            - '[0-9]+.[0-9]+.x'
            - 'refs/pull/*'
jobs:
    ci:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                dependencies:
                    - "lowest"
                    - "highest"
                php-version:
                    - "7.3"
                    - "7.4"
                    - "8.0"
                    - "8.1"
                    - "8.2"
                    - "8.3"
                operating-system:
                    - "ubuntu-latest"

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  coverage: pcov
                  php-version: ${{ matrix.php-version }}
                  ini-values: memory_limit=-1
                  tools: composer:v2, cs2pr

            - name: Get Composer cache directory
              id: composer-cache
              run: |
                  echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                  path: |
                      ${{ steps.composer-cache.outputs.dir }}
                      vendor
                  key: "php-${{ matrix.php-version }}-${{ matrix.dependencies }}"
                  restore-keys: "php-${{ matrix.php-version }}-${{ matrix.dependencies }}"

            - name: Install lowest dependencies
              if: ${{ matrix.dependencies == 'lowest' }}
              run: "composer update --prefer-lowest --no-interaction --no-progress --no-suggest"

            - name: Install highest dependencies
              if: ${{ matrix.dependencies == 'highest' }}
              run: "composer update --no-interaction --no-progress --no-suggest"

            - name: Run phpcs
              run: "vendor/bin/phpcs -q --report=checkstyle | cs2pr"

            - name: Run PHPUnit
              run: "vendor/bin/phpunit"
